site_name: Diffie-Hellman Key Exchange

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Diffie-Hellman Key Exchange: index.md
  - Getting Started: getting_started.md
  - API Reference: api_reference.md