name: Clean Up and Build Docs
on:
  push:
    branches:
      - main
jobs:
  clean_up_and_build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: |
          pip install -r requirements/build_docs.txt
          pip install -r requirements/clean_up.txt
      - name: Auto-format code with Ruff
        run: ruff format .
      - name: Commit auto-formatted scripts
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          (
            if [ -n "$(git status --porcelain)" ]; 
              then 
                TEMP_BRANCH_NAME=github_actions_bot_$(date '+%Y_%m_%d_%H_%M_%S')
                git checkout -b $TEMP_BRANCH_NAME
                git commit -a -m "style() github-actions[bot] auto-formatted code"
                git push --set-upstream origin $TEMP_BRANCH_NAME
                gh pr create --title 'code auto-formatting' --body 'auto pull request by github-actions[bot]'
                gh pr merge --auto
              else 
                echo "No changes to commit!"
            fi
          )
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
        continue-on-error: true