name: Run Tests
on:
  workflow_dispatch:
  pull_request:
   branches:
     - main
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: pip install -r requirements/tests.txt
      - name: Run Tests
        run: |
          python -m pytest tests/unit
          python -m pytest tests/integration
          python -m pytest tests/end_to_end
          mypy diffie_hellman_merkle
          python -m doctest diffie_hellman_merkle/helpers.py
